### PR TITLE
Fix variadic functions implementation

### LINKED ISSUE #117: LibOS and Pal don't build on Ubuntu 17.10
I tried to build Graphene on Ubuntu 17.10, but it failed with the following errors:

### LibOS
```
graphene/LibOS$ make
Building glibc, may take a while to finish. Warning messages may show up. If this process terminates with failures, see "glibc-build/build.log" for more information.
cd glibc-build && ((make >> build.log) 2>&1 | tee -a build.log)
/usr/bin/ld: graphene/LibOS/glibc-build/csu/crt1.o: relocation R_X86_64_32S against symbol `__libc_csu_fini' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/7/crtbegin.o: relocation R_X86_64_32 against hidden symbol `__TMC_END__' can not be used when making a shared object
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
make[3]: *** [graphene/LibOS/glibc-build/iconv/iconvconfig] Error 1
make[2]: *** [iconv/others] Error 2
make[1]: *** [all] Error 2
make -C shim all
make[1]: Entering directory 'graphene/LibOS/shim'
make all -C src
make[2]: Entering directory 'graphene/LibOS/shim/src'
[ shim_parser.o ]
In file included from ../include/shim_internal.h:66:0,
                 from shim_parser.c:27:
shim_parser.c: In function ‘parse_syscall_args’:
shim_parser.c:451:40: error: first argument to ‘va_arg’ not of type ‘va_list’
     const char * arg_type = va_arg(ap, const char *);
                                        ^
shim_parser.c: In function ‘skip_syscall_args’:
shim_parser.c:463:41: error: first argument to ‘va_arg’ not of type ‘va_list’
     const char * arg_type = va_arg (ap, const char *);
                                         ^
shim_parser.c:466:20: error: first argument to ‘va_arg’ not of type ‘va_list’
         va_arg(ap, const char *);
                    ^
shim_parser.c:468:20: error: first argument to ‘va_arg’ not of type ‘va_list’
         va_arg(ap, void *);
                    ^
shim_parser.c:470:20: error: first argument to ‘va_arg’ not of type ‘va_list’
         va_arg(ap, int);
                    ^
Makefile:109: recipe for target 'shim_parser.o' failed
make[2]: *** [shim_parser.o] Error 1
make[2]: Leaving directory 'graphene/LibOS/shim/src'
Makefile:13: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory 'graphene/LibOS/shim'
Makefile:13: recipe for target 'all' failed
make: *** [all] Error 2
```
### Pal
```
graphene/Pal/src$ make
Building target: Linux
make -C ../lib target=graphene/Pal/src/.lib/
make[1]: Entering directory 'graphene/Pal/lib'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory 'graphene/Pal/lib'
make[1]: Entering directory 'graphene/Pal/src/host/Linux'
[ host/Linux/db_pipes.o ]
In file included from /usr/include/x86_64-linux-gnu/bits/types/sigset_t.h:4:0,
                 from /usr/include/x86_64-linux-gnu/sys/select.h:33,
                 from /usr/include/x86_64-linux-gnu/sys/types.h:197,
                 from /usr/include/x86_64-linux-gnu/bits/socket.h:29,
                 from /usr/include/x86_64-linux-gnu/sys/socket.h:33,
                 from db_pipes.c:42:
/usr/include/x86_64-linux-gnu/bits/types/__sigset_t.h:8:3: error: conflicting types for ‘__sigset_t’
 } __sigset_t;
   ^~~~~~~~~~
In file included from pal_linux.h:32:0,
                 from db_pipes.c:31:
include/sigset.h:36:5: note: previous declaration of ‘__sigset_t’ was here
   } __sigset_t;
     ^~~~~~~~~~
Makefile:43: recipe for target 'db_pipes.o' failed
make[1]: *** [db_pipes.o] Error 1
make[1]: Leaving directory 'graphene/Pal/src/host/Linux'
Makefile:94: recipe for target 'host/Linux/libpal-Linux.a' failed
make: *** [host/Linux/libpal-Linux.a] Error 2
```

### PR DESCRIPTION
**Pull request by mkow**
Partially addresses #117.

### CODE REVIEW

**Comment by neilbd** [comment]
Can one of the admins verify this patch?

**Comment by mkow** [comment]
Hmm, it now compiles under gcc 7.2.0 on Ubuntu 16.04, but still not on Ubuntu 17.10. I'll fix that in a next commit.

**Comment by mkow** [comment]
Hmm, the problem with redefinition of `__sigset_t` seems to be a bit harder to fix. Any idea how do to it?

**Comment by donporter** [comment]
Test this please

**Comment by donporter** [comment]
Ok to test

**Comment by donporter** [comment]
Test this please

**Comment by donporter** [comment]
Re-run with tip of this branch (12/5)
Only going to test SGX, as Jenkins now tests the Linux host.

---
- [x] Describe the testing setup:
  - [x] **Code version:** branch omeg/master
  - [x] **Linux kernel version:** 4.4.0-98-generic
  - [x] **Ubuntu version:** 16.04.03 LTS
  - [x] **SGX SDK version:** 01org/linux-sgx@cdf563
  - [x] **SGX driver version:** 01org/linux-sgx-driver@e3e42d4
---
- [x] **PAL**
  - [x] **Linux+SGX host**
    - [x] **Compilation:** passed
    - [ ] **Regression tests:** 
---
- [x] **Library OS**
    - [x] **Compilation:** passed
    - [x] **Linux-SGX host**
      - [ ] **Regression tests:** 
      - [ ] **LTP tests:** Not fully supported yet
---
- [ ] **Applications**
    - [x] **Linux-SGX host**
      - [ ] **LMBench:** lat_proc shell gets a segmentation fault.  lat_tcp, bw_tcp 127.0.0.1 gets permission denied messages in connect; bw_pipe has an occasional failure with the signal queue overflowing (same problems observed on master), an occasional vma assertion blows.  - generally, pretty flaky on SGX, but not necessarily different than master.
      - [ ] **GCC:** 
      - [ ] **Lighttpd:** Fails with memory allocation issue (same on master)
      - [ ] **Apache:**
      - [ ] **Python:**
