### PR TITLE
[Pal] Fix GCC -Wmaybe-uninitialized warning

### PR DESCRIPTION
**Pull request by Time0o**
Fixes a warning/error in Pal/src/db_rtld.c that prevents building
with GCC 11.1.0.

## Description of the changes

Trying to compile with `GCC 11.1.0` results in the following warning/error:

```
../Pal/src/db_rtld.c: In function ‘map_elf_object_by_handle.constprop’:
../Pal/src/db_rtld.c:206:43: error: ‘(((char *)c + 16))[461168601842738789].mapend’ may be used uninitialized [-Werror=maybe-uninitialized]
  206 |                 if (nloadcmds > 1 && c[-1].mapend != c->mapstart)
```

This pull request fixes that without making any changes in functionality.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2651)

### CODE REVIEW

**Review by pwmarcz — APPROVED** [review]
Jenkins, test this please

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2651#-:-MhIw6c5AUerhk7sGIel:bkop2df)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by mkow — DISMISSED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2651)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Comment by mkow** [comment]
Jenkins, test this please

**Review by dimakuv — DISMISSED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2651)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by mkow — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2651)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2651#-MhOdHyH7FCzr62QvvCy:-MhOdHyI0_x5ny5c9Af3:b-6b9suy) (no related file):*
@Time0o for the future: Please prefix your PR branches with your nick, otherwise it's more PITA for us to rebase them before merging. And especially don't do them from "master" branch, you won't be able now to create other PRs at the same time, and `git pull` from oscarlab in your repo won't work until we do the rebase (which I just did, so it should work again).

---

**Comment by mkow** [comment]
Jenkins, retest this please

**Review by pwmarcz — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2651)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2651)* status: :shipit: complete! all files reviewed, all discussions resolved
