### PR TITLE
[LibOS,Pal] Make Graphene build on Clear Linux and GCC 9.3

### LINKED ISSUE #1442: [Pal/Linux-SGX] libpal.so build uses system Glibc headers
## Description of the problem

People report issues with building Graphene-SGX on Clear Linux. Clear Linux has a slightly tweaked version of Glibc (it is built with `FORTIFY_SOURCE`), and so its system Glibc headers are slightly different than those on Debian/Ubuntu.

In particular, the linking stage of Linux-SGX PAL does this:
```
ld -shared -nostdlib -z combreloc -z defs --version-script host/Linux-SGX/pal.map -T host/Linux-SGX/enclave.lds --hash-style=gnu -z relro -z now  -o host/Linux-SGX/libpal.so host/Linux-SGX/.obj/db_events.o host/Linux-SGX/.obj/db_exception.o host/Linux-SGX/.obj/db_main.o host/Linux-SGX/.obj/db_memory.o host/Linux-SGX/.obj/db_misc.o host/Linux-SGX/.obj/db_mutex.o host/Linux-SGX/.obj/db_object.o host/Linux-SGX/.obj/db_process.o host/Linux-SGX/.obj/db_rtld.o host/Linux-SGX/.obj/db_streams.o host/Linux-SGX/.obj/db_threading.o host/Linux-SGX/.obj/pal_error.o host/Linux-SGX/.obj/printf.o host/Linux-SGX/.obj/slab.o host/Linux-SGX/libpal-Linux-SGX.a host/Linux-SGX/.lib/graphene-lib.a -soname libpal.so
```

Notice `-nostdlib`: Linux-SGX PAL doesn't use system's Glibc. However, there is no `-nostdinc`, and so Linux-SGX PAL uses system's **Glibc headers**. And since they are slightly different, in particular this kind of errors happen:
```
ld: /usr/include/bits/string_fortified.h:34: undefined reference to `__memcpy_chk`
```

Recall that `__memcpy_chk()` is the FORTIFIED version of `memcpy()`. So we included the definition of this function but didn't provide its implementation.

**Required solution:** apply `-nostdinc` to our builds and provide our own Glibc headers.

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

This PR makes Graphene to correctly build and run (most) tests on Clear Linux with GCC 9.3. In particular:

- [Makefiles] Make Graphene build on Clear Linux. Clear Linux ships with Glibc built with `-Wp,-DFORTIFY_SOURCE=2`. This overwrites Graphene's `-UFORTIFY_SOURCE` because of the quirk in how GCC applies arguments (first without Wp, then with Wp). This commit updates Makefiles to use `-Wp,-UFORTIFY_SOURCE`.

- [LibOS,Pal] Make Graphene build with GCC 9.3. GCC 9.3 adds more static checks on C headers and sources. This commit fixes all detected issues (mainly possible NULL pointer dereferences).

**NOTE:** Some tests (especially LibOS tests) require changes in manifests to correctly run on Clear Linux. In particular, some paths in mount points are different, as well as some library names. This PR does *not* attempt to change the manifests.

Fixes #1442.

## How to test this PR? 

Normal Ubuntu build and all tests must pass. You can manually test this PR on Clear Linux.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1455)

### CODE REVIEW

**Comment by dimakuv** [comment]
Jenkins, retest Jenkins-Debug-18.04 please (`writev01` LTP test timed out)

**Comment by dimakuv** [comment]
Jenkins, retest Jenkins-18.04 please (lmbench internet connectivity)

**Comment by dimakuv** [comment]
Jenkins, retest Jenkins-SGX-apps please (lmbench internet connectivity)

**Comment by dimakuv** [comment]
Jenkins, retest Jenkins please (LMBench internet connectivity)
