### ISSUE TITLE
LibOS and Pal don't build on Ubuntu 17.10

### ISSUE THREAD

**Issue by mkow** [oscarlab/graphene#117]
I tried to build Graphene on Ubuntu 17.10, but it failed with the following errors:

### LibOS
```
graphene/LibOS$ make
Building glibc, may take a while to finish. Warning messages may show up. If this process terminates with failures, see "glibc-build/build.log" for more information.
cd glibc-build && ((make >> build.log) 2>&1 | tee -a build.log)
/usr/bin/ld: graphene/LibOS/glibc-build/csu/crt1.o: relocation R_X86_64_32S against symbol `__libc_csu_fini' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/7/crtbegin.o: relocation R_X86_64_32 against hidden symbol `__TMC_END__' can not be used when making a shared object
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
make[3]: *** [graphene/LibOS/glibc-build/iconv/iconvconfig] Error 1
make[2]: *** [iconv/others] Error 2
make[1]: *** [all] Error 2
make -C shim all
make[1]: Entering directory 'graphene/LibOS/shim'
make all -C src
make[2]: Entering directory 'graphene/LibOS/shim/src'
[ shim_parser.o ]
In file included from ../include/shim_internal.h:66:0,
                 from shim_parser.c:27:
shim_parser.c: In function ‘parse_syscall_args’:
shim_parser.c:451:40: error: first argument to ‘va_arg’ not of type ‘va_list’
     const char * arg_type = va_arg(ap, const char *);
                                        ^
shim_parser.c: In function ‘skip_syscall_args’:
shim_parser.c:463:41: error: first argument to ‘va_arg’ not of type ‘va_list’
     const char * arg_type = va_arg (ap, const char *);
                                         ^
shim_parser.c:466:20: error: first argument to ‘va_arg’ not of type ‘va_list’
         va_arg(ap, const char *);
                    ^
shim_parser.c:468:20: error: first argument to ‘va_arg’ not of type ‘va_list’
         va_arg(ap, void *);
                    ^
shim_parser.c:470:20: error: first argument to ‘va_arg’ not of type ‘va_list’
         va_arg(ap, int);
                    ^
Makefile:109: recipe for target 'shim_parser.o' failed
make[2]: *** [shim_parser.o] Error 1
make[2]: Leaving directory 'graphene/LibOS/shim/src'
Makefile:13: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory 'graphene/LibOS/shim'
Makefile:13: recipe for target 'all' failed
make: *** [all] Error 2
```
### Pal
```
graphene/Pal/src$ make
Building target: Linux
make -C ../lib target=graphene/Pal/src/.lib/
make[1]: Entering directory 'graphene/Pal/lib'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory 'graphene/Pal/lib'
make[1]: Entering directory 'graphene/Pal/src/host/Linux'
[ host/Linux/db_pipes.o ]
In file included from /usr/include/x86_64-linux-gnu/bits/types/sigset_t.h:4:0,
                 from /usr/include/x86_64-linux-gnu/sys/select.h:33,
                 from /usr/include/x86_64-linux-gnu/sys/types.h:197,
                 from /usr/include/x86_64-linux-gnu/bits/socket.h:29,
                 from /usr/include/x86_64-linux-gnu/sys/socket.h:33,
                 from db_pipes.c:42:
/usr/include/x86_64-linux-gnu/bits/types/__sigset_t.h:8:3: error: conflicting types for ‘__sigset_t’
 } __sigset_t;
   ^~~~~~~~~~
In file included from pal_linux.h:32:0,
                 from db_pipes.c:31:
include/sigset.h:36:5: note: previous declaration of ‘__sigset_t’ was here
   } __sigset_t;
     ^~~~~~~~~~
Makefile:43: recipe for target 'db_pipes.o' failed
make[1]: *** [db_pipes.o] Error 1
make[1]: Leaving directory 'graphene/Pal/src/host/Linux'
Makefile:94: recipe for target 'host/Linux/libpal-Linux.a' failed
make: *** [host/Linux/libpal-Linux.a] Error 2
```

**Comment by donporter** [comment]
Note that we don't officially support 17.10, and we probably don't have the capacity to fully take this on yet.  That said, we are happy to get build fixes (thanks!) and, in general, newer versions of gcc tend to flag issues that are worth fixing.  

See if #135 gets you going.

**Comment by mkow** [comment]
Thanks for the fix, but it still doesn't compile. The error is the same:
```
[ host/Linux/db_pipes.o ]
In file included from /usr/include/x86_64-linux-gnu/bits/types/sigset_t.h:4:0,
                 from /usr/include/x86_64-linux-gnu/sys/select.h:33,
                 from /usr/include/x86_64-linux-gnu/sys/types.h:197,
                 from /usr/include/x86_64-linux-gnu/bits/socket.h:29,
                 from /usr/include/x86_64-linux-gnu/sys/socket.h:33,
                 from db_pipes.c:42:
/usr/include/x86_64-linux-gnu/bits/types/__sigset_t.h:8:3: error: conflicting types for ‘__sigset_t’
 } __sigset_t;
   ^~~~~~~~~~
In file included from pal_linux.h:32:0,
                 from db_pipes.c:31:
include/sigset.h:36:5: note: previous declaration of ‘__sigset_t’ was here
   } __sigset_t;
     ^~~~~~~~~~
Makefile:43: recipe for target 'db_pipes.o' failed
```

**Comment by donporter** [comment]
Yup, my first attempt committed the wrong fix.  Try again.
It still doesn't build for me - I hit a different issue on 17.10 with the glibc build that seems harder to fix than I want to get into right now.

**Comment by mkow** [comment]
Ok, this error is fixed now, thanks! I'll look into the other ones after merging this fix.

**Comment by sgx-naors** [comment]
Hi,

I successfully built Graphene-SGX on Ubuntu 17.10.1.
I already talked to Mr. Chia-Che who suggested I create an issue for a problem I found.
Since it wasn't the only issue, I created a [Readme.md ](https://github.com/sgx-naors/Iolite/blob/master/README.md) explaining the process in depth.

Enjoy

**Comment by donporter** [comment]
So is the root of the issue just to use gcc 4.8 (and not a newer version)?  Or were there other issues you had to fix?

**Comment by sgx-naors** [comment]
The latter. The link I provided contains a patch I made.

**Comment by donporter** [comment]
I see.  But no changes to Graphene otherwise - the patch appears to be to the psw/sdk, correct?

Feel free to upstream the patch to the linux-sgx project (of course). :)  

Thanks!

**Comment by cowonthebeach** [comment]
I got bit by this ticket. 
I made the mistake of upgrading to Ubuntu 18.04  (`do-release-upgrade`).  LTS 18.04 uses gcc 7 with PIE and PIC enabled by default.  Now, when graphene builds glibc, it dies:  
```/usr/bin/x86_64-linux-gnu-ld: /home/graphene/dev/graphene-github/LibOS/glibc-build/csu/crt1.o: relocation R_X86_64_32S against symbol `__libc_csu_fini' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/x86_64-linux-gnu-ld: /usr/lib/gcc/x86_64-linux-gnu/7/crtbegin.o: relocation R_X86_64_32 against hidden symbol `__TMC_END__' can not be used when making a PIE object
/usr/bin/x86_64-linux-gnu-ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
make[4]: *** [/home/graphene/dev/graphene-github/LibOS/glibc-build/iconv/iconvconfig] Error 1
make[3]: *** [iconv/others] Error 2
make[2]: *** [all] Error 2
Makefile:20: recipe for target 'glibc-build/Build.success' failed
make[1]: *** [glibc-build/Build.success] Error 2
make[1]: Leaving directory '/home/graphene/dev/graphene-github/LibOS'```

**Comment by chiache** [comment]
Thanks for reporting. I also recently upgraded to 18.04 and ran into this problem. For now, please use GCC 4 or 5 to build Graphene. I will look into a solution for this compatibility issue.

**Comment by cowonthebeach** [comment]
Thanks for the fast response! 
gcc 5 (the one I got from the packet manager at least) is also built with PIE and PIC enabled

**Comment by chiache** [comment]
This issue should be resolved by #241. Please let us know if the the problem continue to emerge.

Thanks!

**Comment by Khallu** [comment]
````
/usr/bin/ld: /home/dev/graphene/LibOS/glibc-build/csu/crt1.o: relocation R_X86_64_32S against symbol `__libc_csu_fini' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/7/crtbegin.o: relocation R_X86_64_32 against hidden symbol `__TMC_END__' can not be used when making a PIE object
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
make[4]: *** [/home/dev/core/graphene/LibOS/glibc-build/iconv/iconvconfig] Error 1
make[3]: *** [iconv/others] Error 2
make[2]: *** [all] Error 2
Makefile:20: recipe for target 'glibc-build/Build.success' failed
make[1]: *** [glibc-build/Build.success] Error 2
make[1]: Leaving directory '/home/dev/core/graphene/LibOS'
Makefile:8: recipe for target 'all' failed
make: *** [all] Error 2
````

Hey Guys, I'm still getting this error. On Ubuntu 18.04
SGX_SDK version 2.7
SGX driver version 2.5
I have tried making with gcc-4.8,5.5, 7.4, 8.3 and 9
